### ISSUE TITLE
Having trouble with Browsefiy & Gulp

### ISSUE THREAD

**Issue by duluca** [angular/router#231]
I have a gulp pipeline and I use browserify, I'm trying to set up the new router, but my template is not rendering at all. In my index.html I only reference the minified file and nothing else. 

I should add i'm using http://angular.github.io/router/getting-started as my starting example and I can't get home.html to render. I haven't created the detail routes.

Any suggestions?

**Comment by rohanrehman** [comment]
have you created the home component?

**Comment by btford** [comment]
Can you please provide a reproduction via [jsbin](http://jsbin.com/), [plnkr.co](http://plnkr.co), or [jsfiddle](http://jsfiddle.net/)?

This saves me a lot of time. Thanks!

**Comment by btford** [comment]
Actually, ecfaf24b2d2a0b616cd191054d769a583c870b94 in master should solve this. The next release should do the right thing when you `require('angular-new-router');`

**Comment by duluca** [comment]
I thought about doing a plnkr, but trying to get gulp working on there looked like a daunting task :) I manually applied ecfaf24 in my local copy and it didn't seem to have make a difference for me. I'll set up a github repo to reproduce the issue.

**Comment by duluca** [comment]
Here's the reproduction of the issue i'm running into https://github.com/duluca/angular-starter 
After cloning:
npm install
gulp
http-server

**Comment by ulrikaugustsson** [comment]
@btford If it helps this seems to work in 0.5.2 but not in 0.5.3

Also getting this error:
```
Uncaught Error: [$injector:modulerr] Failed to instantiate module wetm due to:
Error: [$injector:modulerr] Failed to instantiate module {} due to:
Error: [ng:areq] Argument 'module' is not a function, got Object
```

`wetm` is my main module
